#!/bin/bash

set -e

BASE_PATH=$1
shift

while [ $# -gt 0 ]; do
  case "$1" in
    --hadoop-version=*)
      HADOOP_VERSION=${1#*=}
      ;;
    --sqoop-version=*)
      SQOOP_VERSION=${1#*=}
      ;;
    --mysql-connector-version=*)
      MYSQL_CONNECTOR_VERSION=${1#*=}
      ;;
    *)
      printf "Error: Invalid argument: %s\n" "$1"
      exit 1
  esac
  shift
done

SQOOP_HOME=/usr/lib/sqoop

install_sqoop() {
  APACHE_MIRROR=www.apache.org
  HADOOP_VERSION=${HADOOP_VERSION:-1.0.0}
  SQOOP_VERSION=${SQOOP_VERSION:-1.4.6}
  SQOOP_RELEASE=sqoop-$SQOOP_VERSION.bin__hadoop-$HADOOP_VERSION
  SQOOP_RELEASE_FILENAME=$SQOOP_RELEASE.tar.gz

  wget http://$APACHE_MIRROR/dist/sqoop/$SQOOP_VERSION/$SQOOP_RELEASE_FILENAME
  tar -xzf $SQOOP_RELEASE_FILENAME
  sudo mv $SQOOP_RELEASE $SQOOP_HOME
  sudo ln -s $SQOOP_HOME/bin/sqoop /usr/bin/sqoop
}

install_sqoop_mysql_connector() {
  MYSQL_CONNECTOR_VERSION=${MYSQL_CONNECTOR_VERSION:-5.1.35}
  MYSQL_CONNECTOR_RELEASE=mysql-connector-java-$MYSQL_CONNECTOR_VERSION
  MYSQL_CONNECTOR_FILENAME=$MYSQL_CONNECTOR_RELEASE.tar.gz
  MYSQL_CONNECTOR_S3_URL=$BASE_PATH/$MYSQL_CONNECTOR_FILENAME
  SQOOP_LIB=$SQOOP_HOME/lib

  hadoop dfs -get $MYSQL_CONNECTOR_S3_URL ./$MYSQL_CONNECTOR_FILENAME
  tar -xzf $MYSQL_CONNECTOR_FILENAME
  mkdir -p $SQOOP_LIB
  sudo cp $MYSQL_CONNECTOR_RELEASE/$MYSQL_CONNECTOR_RELEASE-bin.jar $SQOOP_LIB/
}

type sqoop || install_sqoop
install_sqoop_mysql_connector
