---

- name: Provision cluster
  hosts: localhost
  gather_facts: False
  vars:
    # The following vars should probably be overridden
    - name: ETL
    - master_instance_num: 1
    - master_instance_type: m1.medium
    - core_instance_num: 1
    - core_instance_type: m1.medium
    - task_instance_num: 1
    - task_instance_type: m1.medium
    - task_instance_bid: 0.03
    - instance_groups:
        master:
          num_instances: "{{ master_instance_num }}"
          type: "{{ master_instance_type }}"
          market: ON_DEMAND
        core:
          num_instances: "{{ core_instance_num }}"
          type: "{{ core_instance_type }}"
          market: ON_DEMAND
        task:
          num_instances: "{{ task_instance_num }}"
          type: "{{ task_instance_type }}"
          market: SPOT
          bidprice: "{{ task_instance_bid }}"
    - bootstrap_actions: {}
    - steps: []
    - applications: []
    - configurations: []
    - ec2_attributes: {}
    - region: 'us-east-1'
    - keypair_name: "{{ lookup('env', 'AWS_KEYPAIR_NAME') }}"
    - role: emr
    - ami_version: 2.4.11
    - release_label: ''
    - vpc_subnet_id: !!null
    - user_info: []
    - log_uri: !!null
  tasks:
    - name: provision EMR cluster
      local_action:
        module: emr
        name: "{{ name }}"
        region: "{{ region }}"
        keypair_name: "{{ keypair_name }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        log_uri: "{{ log_uri }}"
        visible_to_all_users: yes
        job_flow_role: "{{ role }}"
        ami_version: "{{ ami_version }}"
        release_label: "{{ release_label }}"
        instance_groups: $instance_groups
        bootstrap_actions: $bootstrap_actions
        steps: $steps
        applications: $applications
        configurations: $configurations
        ec2_attributes: $ec2_attributes
      register: jobflow

    - name: add master to group
      local_action: >
        add_host hostname={{ jobflow.master_private_ip }} groupname=launched_master ansible_ssh_user=hadoop ansible_connection=ssh

    - name: display master IP address
      debug: msg={{ jobflow.master_private_ip }}

    - name: display job flow ID
      debug: msg={{ jobflow.jobflow_id }}


- name: Configure SSH access to cluster
  hosts: launched_master
  gather_facts: False
  sudo: True
  roles:
    - user
